# Generated by Django 5.2.3 on 2025-06-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionbox',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='subscriptionbox',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='ScheduledItem',
        ),
        migrations.DeleteModel(
            name='SubscriptionBox',
        ),
    ]
