# Generated by Django 5.2.3 on 2025-06-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionbox',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('twice_a_month', 'Twice a Month'), ('monthly', 'onthly')], max_length=20),
        ),
    ]
